### ISSUE TITLE
Firefox tab-switch issue

### ISSUE THREAD

**Issue by Meghrikyan** [golemhq/golem#172]
Preconditions:
Browser: Firefox. 
(Element A) - any existing element from 1-st tab
(Element B) - any existing element from 2-nd tab
Steps to reproduce:
1. Open 2 tab-s.
2. Navigate to 1-st tab search (wait_for_element_present) Element A
3. Navigate to 2-nd tab, search Element B 
    Expected result: Element found
    Actual result: Element not found
4. Search existing element from 1-st tab by xpath
    Expected result: Element not found
    Actual result: Element not found
5. Refresh tab 2.
Search existing element from 2-nd tab by xpath
    Expected result: Element found
    Actual result: Element found

DOM is not loaded after switching to the tab.

**Comment by luciano-renzi** [comment]
Hi @Meghrikyan. It looks like the problem is Firefox/geckodriver does not wait for the new tab to load. This is a known issue or a different implementation of webdriver between Chrome and Firefox. See the following issues:

- https://github.com/mozilla/geckodriver/issues/308
- https://github.com/mozilla/geckodriver/issues/878
- https://github.com/SeleniumHQ/selenium/issues/4570

As an example, the following test works only if I "wait_for_window_present_by_title" before switching. You ou should check that the tab finished loading as well. Should this be patched from the Golem side? probably not.

```
def test(data):
    navigate('https://www.web-playground.net/tabs/')
    assert_title('Web Playground - Tabs')
    click('#openTab')
    wait_for_window_present_by_title('Tab')
    assert_amount_of_windows(2)
    switch_to_next_window()
    assert_title('Tab')
    assert_element_present('#button-one')
    switch_to_next_window()
    assert_title('Web Playground - Tabs')
    assert_element_present('#openTab')

```

**Comment by Meghrikyan** [comment]
Thanks, will take into consideration for this type of tests
