### ISSUE TITLE
Importing Test Data from External Files(Excel/CSV)

### ISSUE THREAD

**Issue by vishal-agg** [golemhq/golem#44]
How can user can import  test data from External Files(Excel/CSV) ?
This is especially helpful when test data is created and handed over by separate manual testers/BAs in the team.

**Comment by lucianopuccio** [comment]
Currently when you create a test, a csv file with the same name is created, and you can populate it manually or using the GUI (the table at the bottom of the test builder). So you have 1 csv per each test.
Data that belongs to the environment like the url, should go to the environments.json
Data that belongs to the project itself (global data) should go to a project_data.json (this is not yet implemented)

The structure is as follows:
```
project/
      tests/
            my_test.py
      data/
            my_test.csv
```

The other thing I'm planning is to put the data file in the same folder of the test as it might be easier to find, especially when dealing with folders and subfolders.

thanks!

**Comment by Meghrikyan** [comment]
@luciano-renzi Hello, If you add an ability to get Test Case file path in Test Case, we can re-work this string and get required path in the folder, as it is possible to do from Page Objects. 
This works from function inside of page object(pages/... .py): 
path.join(path.dirname(path.dirname(path.realpath( __file__ ))), 'data\\' + FName)

**Comment by DowneyTung** [comment]
hey @luciano-renzi is that possible that we add a feature that the test could use multiple datasets. Usually we want to run one test for multiple environments(like QA, Stage, Prod), and the only thing different is the dataset using for each environment. 
 instead of the current one csv datasets for one test. 
I would think a way to improve this would be like this:
1. create a folder that share the same name with the test case
2.Under the folder, create sub-folder named after environment variable like QA, Stage, Prod
3.Under each subfolder will have the csv dataset for that env

So, the structure would be look like this
some_test.py
some_test\
         \QA
              some_test.csv
         \Stage
              some_test.csv
          \Prod
              some_test.csv
           
Let me know if you have any other thoughts or ideas. 
Thanks

**Comment by luciano-renzi** [comment]
The environments.json can be used for environment specific data. But I'll keep this in mind. Thanks
