### ISSUE TITLE
Chrome/chrome-headless skipping commands

### ISSUE THREAD

**Issue by ninoM** [golemhq/golem#65]
First of all, thanks so much for this open source project!

So when I run tests on chrome/chrome-headless, it sometimes skips commands. 

```python
    ...
    banner.check_tab(banner.browse_now_button, "First tab")
    # Check third tab
    click(banner.third_tab)
    banner.check_tab(banner.services_button, "Third tab")
    # Check second tab and modal when clicking button on this tab
    click(banner.second_tab)
    banner.check_tab(banner.submit_listing_button, "Second tab")
    ...
```

it will skip the 6th line of code and go straight to checking an element.
banner.check_tab is a function in a 'page'.

Here I highlight the execution_console.log lines that are important
> 6:40:06.400 INFO Take screenshot First tab
> 16:40:07.423 INFO Verify the element 'Browse now button' is visible
> 16:40:07.465 INFO Click Third tab banner
> **16:40:07.510 INFO Take screenshot Third tab**
> **16:40:12.825 INFO Verify the element 'Services button' is visible**
> **16:40:12.836 INFO Take screenshot error**
> 16:40:13.385 ERROR An error ocurred:
> Traceback (most recent call last):
>   File "/home/Glaydur/environments/golem_test/lib/python3.5/site-packages/golem/test_runner/test_runner.py", line 124, in run_test
>     test_module.test(execution.data)
>   File "/home/Glaydur/dev/[redacted]/projects/[redacted]/tests/banner.py", line 27, in test
>     banner.check_tab(banner.services_button, "Third tab")
>   File "/home/Glaydur/dev/[redacted]/projects/[redacted]/pages/banner.py", line 14, in check_tab
>     actions.verify_is_visible(element)
>   File "/home/Glaydur/environments/golem_test/lib/python3.5/site-packages/golem/actions.py", line 330, in verify_is_visible
>     raise Exception('Element is not visible')
> Exception: Element is not visible

This doesn't happen all the time (just every time I change the test code). I find that if I run the test in firefox first then in chrome/chrome-headless it would work fine (until I change the test code).

**Comment by lucianopuccio** [comment]
Hi nimoM, from what I see in the log, the problem seems to be between these two lines:
```
click(banner.third_tab)
banner.check_tab(banner.services_button, "Third tab")
```
It's not actually skipping commands, it's just that chromedriver might be faster than firefox and there's no mechanism for Golem to wait for the third tab to be visible, (assuming it's not instantaneously visible after clicking banner.third_tab). 

Golem waits for the element to exist if you assign some time in the "implicit_wait" setting but Golem won't wait for the element to be visible. Just a remainder that in Selenium exists != visible

To see if this is the case, you can try adding a fixed wait *actions.wait(seconds)* or an explicit wait (recommended), something like this: [actions.wait_for_element_visible](http://golem-framework.readthedocs.io/en/latest/golem-actions.html#wait-for-element-visible-element-timeout-20)

Let me know if this doesn't help

**Comment by ninoM** [comment]
I lucianopuccio, thanks for the reply! The ones I'm clicking on (banner.third_tab, banner.second_tab) are tabs so they're always visible and don't disappear. I did try your recommendation of setting an explicit wait time and it spit out the error that the element isn't visible even though I'm staring at it (chrome mode). The other weird thing is that when I use firefox as browser then switch back to chrome/chrome-headless, it behaves for a little while. Would be grateful for any more suggestions :)

**Comment by luciano-renzi** [comment]
This is an known issue with Geckodriver, it does not wait for page or tab to load after a click.
